[package]
name = "yew_training_project"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
gloo = "0.11.0"
serde = "1.0.203"
serde_json = "1.0.117"
yew = { version = "0.21.0", features = ["csr", "hydration", "ssr"] }
